#! /bin/sh

./Configure -des \
	    -Doptimize=-O2 \
	    -Dmyhostname=localhost \
	    -Dperladmin=root@localhost \
	    -Dcc=gcc \
	    -Dcf_by='Open Embedded' \
	    -Dinstallprefix=/usr \
	    -Dprefix=/usr \
	    -Dvendorprefix=/usr \
	    -Dsiteprefix=/usr \
	    -Dotherlibdirs=/usr/lib/perl/5.22.1 \
	    -Duseshrplib \
	    -Dusethreads \
	    -Duseithreads \
	    -Duselargefiles \
	    -Ud_dosuid \
	    -Dd_semctl_semun \
	    -Ui_db \
	    -Ui_ndbm \
	    -Ui_gdbm \
	    -Di_shadow \
	    -Di_syslog \
	    -Dman3ext=3pm \
	    -Duseperlio \
	    -Dinstallusrbinperl \
	    -Ubincompat5005 \
	    -Uversiononly \
	    -Dpager='/usr/bin/less -isr'